FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

RUN dpkg --add-architecture arm64
RUN apt-get update

RUN apt-get install -y --no-install-recommends \
    libssl-dev:arm64 \
    libsqlite3-dev:arm64 \
    librdkafka-dev:arm64 \
    pkg-config

ENV PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig
ENV PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
